<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.0" />
    <PackageReference Include="Moq" Version="4.20.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HackerNews.Api\HackerNews.Api.csproj" />
    <ProjectReference Include="..\HackerNews.Aplication\HackerNews.Aplication.csproj" />
    <ProjectReference Include="..\HackerNews.Domain\HackerNews.Domain.csproj" />
    <ProjectReference Include="..\HackerNews.Infra\HackerNews.Infra.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
